spring.application.name=StarBank
application.recommendations-db.url=jdbc:h2:file:./transaction;ACCESS_MODE_DATA=r

logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.h2=TRACE

spring.data.jdbc.repositories.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
