openapi: 3.0.1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /rule:
    get:
      tags:
      - rule-controller
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    post:
      tags:
      - rule-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DynamicRuleDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DynamicRuleDto"
  /management/clear-caches:
    post:
      tags:
      - management-controller
      operationId: clearCaches
      responses:
        "200":
          description: OK
  /rule/stats:
    get:
      tags:
      - rule-stats-controller
      operationId: getStats
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    additionalProperties:
                      type: object
  /recommendation/{userId}:
    get:
      tags:
      - recommendation-controller
      operationId: getRecommendation
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecommendationResponse"
  /management/info:
    get:
      tags:
      - management-controller
      operationId: getInfo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /rule/{productId}:
    delete:
      tags:
      - rule-controller
      operationId: delete
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
components:
  schemas:
    DynamicRuleDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: string
        productName:
          type: string
        productText:
          type: string
        rule:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
    RecommendationDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        text:
          type: string
    RecommendationResponse:
      type: object
      properties:
        user_id:
          type: string
        recommendations:
          type: array
          items:
            $ref: "#/components/schemas/RecommendationDto"
